### PR TITLE
Fix rendering empty crud lists

### PR DESCRIPTION
**Pull request by lmars**
My previous fix for this (#4) did not work as the empty lists were not equal to `nil`, it was just that the json encoder was encoding the (unallocated?) lists as `null`.

I tried `if len(list) == 0` but because `list` is of type `interface{}` I got:

```
# github.com/flynn/flynn-controller
./crud.go:76: invalid argument list (type interface {}) for len
```

So instead I am explicitly allocating the lists (I think).

I did attempt to write a test for this but I was tying myself in knots, so I have verified it with curl:

```
vagrant@flynn:/vagrant/controller$ curl -k -u ":${KEY}" https://localhost/keys                                                                                   
[]
```

### CODE REVIEW

**Comment by titanous** [comment]
Ah, the problem was that the interface was not nil, as it contained a nil slice.

**Comment by titanous** [comment]
The commit needs a DCO sign-off.

**Comment by lmars** [comment]
DCO sign-off added

**Comment by titanous** [comment]
Thanks!

**Pull request merged**
